// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
aws_app_analytics : 'enable',
aws_cloud_logic : 'enable',
aws_cloud_logic_custom : '[{"id":"jv72ml6yzk","name":"userProfile","description":"api to use to modify user profile","endpoint":"https://jv72ml6yzk.execute-api.eu-central-1.amazonaws.com/Development","region":"eu-central-1","paths":["/driverMode","/startPoint","/endPoint","/driverMode/123","/startPoint/123","/endPoint/123"]}]',
aws_cognito_identity_pool_id : 'eu-central-1:fe9c076b-1e38-4eed-86c1-cb981f81b9a1',
aws_cognito_region : 'eu-central-1',
aws_content_delivery : 'enable',
aws_content_delivery_bucket : 'tralacar-hosting-mobilehub-1555165769',
aws_content_delivery_bucket_region : 'eu-central-1',
aws_content_delivery_cloudfront : 'enable',
aws_content_delivery_cloudfront_domain : 'd10u8o2ct73j9o.cloudfront.net',
aws_dynamodb : 'enable',
aws_dynamodb_all_tables_region : 'eu-central-1',
aws_dynamodb_table_schemas : '[{"tableName":"tralacar-mobilehub-1555165769-UserProfiles","attributes":[{"name":"userId","type":"S"},{"name":"driverMode","type":"S"},{"name":"endPoint","type":"N"},{"name":"startPoint","type":"N"}],"indexes":[{"indexName":"DateSorted","hashKey":"userId"}],"region":"eu-central-1","hashKey":"userId","rangeKey":"driverMode"}]',
aws_mandatory_sign_in : 'enable',
aws_mobile_analytics_app_id : '1ba7eb795c614da1b56c909120f20e8f',
aws_project_id : '4b1a0b8f-ec1b-489b-9ff6-1763f541e03c',
aws_project_name : 'Tralacar-2017-12-01-12-17-29',
aws_project_region : 'eu-central-1',
aws_resource_bucket_name : 'tralacar-deployments-mobilehub-1555165769',
aws_resource_name_prefix : 'tralacar-mobilehub-1555165769',
aws_sign_in_enabled : 'enable',
aws_user_pools : 'enable',
aws_user_pools_id : 'eu-central-1_7fbMllgfI',
aws_user_pools_mfa_type : 'OFF',
aws_user_pools_web_client_id : '3iq3vck2uef10lbjibgdej9ob1',
}

export default awsmobile;
var AWS = require('aws-sdk');
AWS.config.region = awsmobile.aws_project_region;
AWS.config.update({customUserAgent: 'MobileHub v0.1'});